version: '2'
services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    networks:
      - wpnet
    ports:
     - "${APP_PORT}:80"
  mysql:
    image: mariadb:10.1
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - wpnet
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASS}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASS}"
networks:
  wpnet:
    driver: "bridge"
volumes:
  mysqldata:
    driver: "local"